### PR TITLE
Enable customising user name and avatar field for display

### PR DESCRIPTION
**Pull request by ben181231**
connect #95

### CODE REVIEW

**Comment by ben181231** [comment]
@howawong This PR is ready to review.

**Comment by howawong** [comment]
This PR is blocked by SkygearIO/skygear-SDK-iOS#144.

**Comment by ben181231** [comment]
Should work after PR SkygearIO/skygear-SDK-iOS#145

**Comment by ben181231** [comment]
@howawong This PR is ready to review again.

**Comment by ben181231** [comment]
Close this first. Open another together with avatar / username ui customization.

**Pull request closed without merging**
