### PR TITLE
Add info on using UI classes in Objective-C code

### PR DESCRIPTION
**Pull request by cheungpat**
connects #201

### CODE REVIEW

**Comment by carmenlau** [comment]
@howawong Would like to know are you able to call the chat ui kit in objective c after adding the header? thanks

**Comment by howawong** [comment]
@carmenlau  partially, as I need to update some other places in the chat SDK when writing the guide. Will update the PR soon.

**Comment by howawong** [comment]
@ben181231  @cheungpat  
Please add the following, thanks!

In `SKYChatUIModelCustomization`
Add `public` to static func `default`() -> SKYChatUIModelCustomization 


In `SKYChatUIModelCustomization`
Add `NSObject` to public class SKYChatUIModelCustomization

**Comment by carmenlau** [comment]
Updated via https://github.com/SkygearIO/chat-SDK-iOS/commit/26d2c0c9b87132371cba6163fa3f2b6826f775be

**Comment by carmenlau** [comment]
Merged via c16cee3

**Pull request closed without merging**
