### PR TITLE
Include JSQMessagesViewController in public headers

### PR DESCRIPTION
**Pull request by cheungpat**
This allows projects using SKYKitChat to use JSQ classes,
which is now embedded in the SKYKitChat.

refs #136

### CODE REVIEW

**Comment by cheungpat** [comment]
This is a partial fix for the problem you are having @tensiuyan

**Comment by cheungpat** [comment]
checkout this branch to evaluate this pull request using the demo project https://github.com/cheungpat/SkygearChat-iOS-Demo/tree/fix-for-1.2.0

**Comment by Steven-Chan** [comment]
> checkout this branch to evaluate this pull request using the demo project https://github.com/cheungpat/SkygearChat-iOS-Demo/tree/fix-for-1.2.0

@cheungpat 

I've just tested with the demo, and it failed to build because the chat sdk in pod cannot find the jsq classes.

I find the source code of jsq classes are not found in the pods folder.

**Comment by Steven-Chan** [comment]
The demo is working after adding a `submodule` flag in pod file. It may be because the demo is not importing a released version. So i would merge this and make a new release first.

**Pull request merged**
