### PR TITLE
Fix multiple UI issues

### PR DESCRIPTION
**Pull request by ben181231**
connect #40
connect #141
connect #143

### CODE REVIEW

**Comment by cheungpat** [comment]
On #40,

I think the intended behaviour described in #40 is that the keyboard should be dismissed when the user tap on “message list blank area”.

I notice that this is commonly implemented in various messaging apps on iOS, so I suppose the original intention was to replicate this behaviour.

The implemented behaviour is that the keyboard is dismissed when scrolling down on the message list.

On #141,

I still see this, missing something?

screen shot 2018-01-03 at 3 38 34 pm

On #143,

I don’t understand why https://github.com/SkygearIO/chat-SDK-iOS/pull/146/commits/76c65a96b808431b3d16a556347deb1fc26d0f87 is related to the issue, but the change looks okay per se.

**Review by cheungpat — CHANGES_REQUESTED** [review]
see earlier comment

**Comment by ben181231** [comment]
@cheungpat 

For #40, I will try to update the PR to achieve tap to dismiss keyboard.

For #141, it works on my testing device. 🙈 🙈  Can you try to run `pod install` in "Example" directory before building to simulator?

For #143, the issue is caused by some inconsistent state. I tried to fix it and do some refactoring.

**Comment by ben181231** [comment]
The PR updated.

**Review by cheungpat — APPROVED** [review]

**Pull request merged**
